DROP DATABASE IF EXISTS smallcloud;

CREATE DATABASE IF NOT EXISTS smallcloud;

GRANT CREATE, ALTER, INSERT, UPDATE, DELETE, DROP, SELECT 
ON smallcloud.* TO 'john'@'localhost' IDENTIFIED BY '1234567';
